### ISSUE TITLE
Add a security policy

### ISSUE THREAD

**Issue by reedy** [martaannaj/RecommenderServer#2]
Can someone please add a security policy to this repo?

See https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

Filed as part of https://phabricator.wikimedia.org/T292110

**Comment by miselico** [comment]
The security policy is now in place here: https://github.com/martaannaj/RecommenderServer/blob/main/SECURITY.md

**Comment by miselico** [comment]
Closing as the security review has now been completed. https://phabricator.wikimedia.org/T292110
