### ISSUE TITLE
Run test pipeline on GitHub CI

### ISSUE THREAD

**Issue by reedy** [martaannaj/RecommenderServer#3]
There are some config files setup around Blubber et al, but none of it is being run (at all?) on GitHub, so it's impossible to see if your commits are passing your own test pipeline

Filed as part of https://phabricator.wikimedia.org/T292110

**Comment by miselico** [comment]
Since 06c4a15e4ffdfaeaff5120eb4ed528bed43b7b4a tests are run as part of the github workflow. Besides, several tests which we had removed with the idea of making the code base more lean were put back into the repository.
