### ISSUE TITLE
Run gosec as a GitHub action

### ISSUE THREAD

**Issue by reedy** [martaannaj/RecommenderServer#4]
https://github.com/securego/gosec#github-action

Filed as part of https://phabricator.wikimedia.org/T292110

**Comment by reedy** [comment]
There might be some overlap with https://github.com/martaannaj/RecommenderServer/issues/5, as golangci-lint can be configured to run gosec (among other things)

**Comment by miselico** [comment]
Is it sufficient to run this upon push to main?

**Comment by reedy** [comment]
That would be the bare minimum, yeah, depending on how active/inactive development is going to be (for example, as of writing, there's not been any commits since July 2021).

However, this doesn't stop improvements to the security scanning library being released, or issues being made public in the used dependancies (and their specific versions), even if the code in this repo isn't changing for months at a time.

Therefore potentially running these on a (semi) regular basis (weekly? daily?) might not be a bad thing.

**Comment by miselico** [comment]
I see. We do not expect a very active development for the time being. I tried configuring it such that they run upon pushing to main, for pull requests and as a weekly cron job.

**Comment by miselico** [comment]
Since 06c4a15 gosec are run as part of the github workflow upon creation of a pull request, merging into main and scheduled once every week on main.
