### ISSUE TITLE
Run a go linter as a GitHub action

### ISSUE THREAD

**Issue by reedy** [martaannaj/RecommenderServer#5]
For example:

https://github.com/golangci/golangci-lint

https://golangci-lint.run/usage/install/#ci-installation

Filed as part of https://phabricator.wikimedia.org/T292110

**Comment by reedy** [comment]
Can potentially do https://github.com/martaannaj/RecommenderServer/issues/4 as part of this issue

**Comment by miselico** [comment]
I have now added golangci-lint to the workflow. It did indicate some issues already, most of them seem trivial to fix. 
I have not investigated how to run tests with this yet.

**Comment by miselico** [comment]
Since 06c4a15 the linter is run as part of the github workflow upon creation of a pull request, merging into main and scheduled once every week on main.
